api:
  build: ./api
  working_dir: /app
  volumes:
    - ./api/src:/app/src
    - ./api/node_modules:/app/node_modules
  ports:
    - "4000:4000"
  command: nodemon --legacy-watch src/index.js
  # command: bash

# db:
#   image: rethinkdb:2.2.1
